print('|welcome in carucater|\n')
print('enter the space please\n')
numb1=float(input('firt number '))
numb2=float(input('second number '))
print('|----------------------------------|\n')
print("Adding :  "+ str(numb1+numb2))
print("subtract :  "+ str(numb1-numb2))
print("Divide :  "+ str(numb1/numb2))
print("multiply :  "+ str(numb1*numb2))
print("modalus :  "+ str(numb1%numb2))